# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-10 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_importdataimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resevationlist',
            name='sale_id',
        ),
        migrations.RemoveField(
            model_name='resevationlist',
            name='user_id',
        ),
        migrations.AddField(
            model_name='resevationlist',
            name='resevation_is_active',
            field=models.BooleanField(default=False, verbose_name='预约成功'),
        ),
        migrations.AddField(
            model_name='resevationlist',
            name='resevation_time',
            field=models.DateTimeField(auto_now=True, verbose_name='预约单生成时间'),
        ),
        migrations.AlterField(
            model_name='resevationlist',
            name='meet_time',
            field=models.DateField(verbose_name='预约时间'),
        ),
    ]
