# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0003_auto_20180710_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='resevationlist',
            name='resevation_uname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
