# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_resevationlist_resevation_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='static/carousels/', verbose_name='轮播图片')),
                ('intro1', models.CharField(max_length=200, verbose_name='标语1')),
                ('intro2', models.CharField(max_length=200, verbose_name='标语2')),
            ],
        ),
    ]
