# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_carousel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': '轮播管理', 'verbose_name_plural': '轮播管理'},
        ),
        migrations.AddField(
            model_name='carousel',
            name='is_use',
            field=models.BooleanField(default=False, verbose_name='是否显示'),
        ),
    ]
