# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20180712_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='pic',
            field=models.ImageField(upload_to='static1/carousels/', verbose_name='轮播图片'),
        ),
    ]
