# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_auto_20180712_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoufu', models.IntegerField(verbose_name='首付（元）')),
                ('yuegong', models.IntegerField(verbose_name='月供（元）')),
                ('qishu', models.IntegerField(default=12, verbose_name='期数')),
                ('weikuan', models.IntegerField(verbose_name='尾款')),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='car.Car', verbose_name='所属车辆')),
            ],
            options={
                'verbose_name': '分期价格管理',
                'verbose_name_plural': '分期价格管理',
            },
        ),
    ]
