# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_carprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carprice',
            name='shoufu',
            field=models.IntegerField(default=4920, verbose_name='首付（元）'),
        ),
        migrations.AlterField(
            model_name='carprice',
            name='weikuan',
            field=models.IntegerField(default=120000, verbose_name='尾款'),
        ),
        migrations.AlterField(
            model_name='carprice',
            name='yuegong',
            field=models.IntegerField(default=3547, verbose_name='月供（元）'),
        ),
    ]
