# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 16:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20180712_2351'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.CharField(max_length=30, verbose_name='类型')),
                ('p_intro', models.CharField(max_length=200, verbose_name='附加说明')),
                ('amount', models.IntegerField(verbose_name='交易金额')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='PayRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paied', models.BooleanField(default=False, verbose_name='是否付清')),
                ('p_type', models.CharField(max_length=30, verbose_name='付款方式')),
                ('cost', models.IntegerField(verbose_name='本次支付金额')),
                ('costed', models.IntegerField(verbose_name='已支付金额')),
                ('car_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.CarPrice', verbose_name='车辆价格')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yue', models.IntegerField(verbose_name='账户余额')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
        ),
    ]
