# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0002_accountrecord_payrecord_useraccount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountrecord',
            options={'verbose_name': '账户记录', 'verbose_name_plural': '账户记录'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': '消息记录', 'verbose_name_plural': '消息记录'},
        ),
        migrations.AlterModelOptions(
            name='payrecord',
            options={'verbose_name': '购买记录', 'verbose_name_plural': '购买记录'},
        ),
        migrations.AlterModelOptions(
            name='useraccount',
            options={'verbose_name': '用户账户', 'verbose_name_plural': '用户账户'},
        ),
        migrations.AddField(
            model_name='accountrecord',
            name='p_time',
            field=models.DateTimeField(auto_now=True, verbose_name='操作时间'),
        ),
    ]
