# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0003_auto_20180713_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrecord',
            name='pay_time',
            field=models.DateTimeField(auto_now=True, verbose_name='付款时间'),
        ),
    ]
