# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0004_payrecord_pay_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecord',
            name='car_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.Car', verbose_name='车型'),
        ),
        migrations.AlterField(
            model_name='payrecord',
            name='cost',
            field=models.IntegerField(null=True, verbose_name='本次支付金额'),
        ),
        migrations.AlterField(
            model_name='payrecord',
            name='costed',
            field=models.IntegerField(null=True, verbose_name='已支付金额'),
        ),
    ]
