# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-07-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0006_auto_20180713_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='yue',
            field=models.IntegerField(default=0, verbose_name='账户余额'),
        ),
    ]
